// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { PostId } from "./PostId";

export type ApiMethod = { "Add": { a: number, b: number, } } | "GetUserState" | "ListChannels" | { "GetPost": { postId: PostId, } } | { "SubscribePost": { postId: PostId, } } | { "UnsubscribePost": { postId: PostId, } } | { "ListPost": { channelId: ChannelId, } } | { "ListComments": { postId: PostId, } };
