// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthMethod = "getAuthUrl" | { "exchangeAuthToken": { state: string, code: string, } } | { "createUser": { refreshToken: string, } };
