// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { PostId } from "./PostId";
import type { UserId } from "./UserId";

export type Context = { user_id: UserId, access_token: string, subscriptions: { [key in ChannelId]?: Array<PostId> }, };
